example/urls.py
from django.contrib import admin
from django.conf.urls import url, include

urlpatterns = [
    url(r'^', include(('user.urls','user'), namespace = 'user')),
    url(r'^admin/', admin.site.urls),
]

user/urls.py
from django.conf.urls import url

from .views import (
    UserList,
    UserDetail,
    UserCreation,
    UserUpdate,
    UserDelete,
)

urlpatterns = [

    url(r'^$', UserList.as_view(), name='list'),
    url(r'^(?P<pk>\d+)$', UserDetail.as_view(), name='detail'),
    url(r'^nuevo$', UserCreation.as_view(), name='new'),
    url(r'^editar/(?P<pk>\d+)$', UserUpdate.as_view(), name='edit'),
    url(r'^borrar/(?P<pk>\d+)$', UserDelete.as_view(), name='delete'),

]

user/models.py
from django.db import models

class User(models.Model):
    name = models.CharField(max_length=140)
    email = models.EmailField()
    phone = models.CharField(max_length=50)

user/views.py
from django.urls import reverse_lazy

from django.views.generic import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import (
    CreateView,
    UpdateView,
    DeleteView
)

from .models import User


class UserList(ListView):
    model = User


class UserDetail(DetailView):
    model = User


class UserCreation(CreateView):
    model = User
    success_url = reverse_lazy('user:list')
    fields = ['name', 'email', 'phone']


class UserUpdate(UpdateView):
    model = User
    success_url = reverse_lazy('user:list')
    fields = ['name', 'email', 'phone']


class UserDelete(DeleteView):
    model = User
    success_url = reverse_lazy('user:list')

user/templates/base.html
{% block head %}
    <title>
    {% block title %} 
    CRUD Usuarios |  
    {% endblock  %} 
    </title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
{% endblock %}
<body>
{% block body %}
    {% block navbar %}
        {% include 'user/navbar.html' %}
    {% endblock  %}
    {% block content %}{% endblock  %}
{% endblock %}       
</body> 

user/templates/user/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <a class="navbar-brand" href="{% url "user:list" %}">Usuarios</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
            <li class="nav-item">
                <a class="nav-link" href="{% url "user:new" %}">Agregar Usuario</a>
            </li>
        </ul>
    </div>
</nav>

user/templates/user/user_confirm_delete.html
{% extends 'base.html' %}
{% block title %}
{{ block.super }}
    Borrar Usuario
{% endblock  %}
{% block content %}
    <form method="post">{% csrf_token %}
        ¿Estás seguro que deseas borrar el Usuario "{{ user.name }}"?
        <input type="submit" value="Borrar" />
    </form>
    <p>
        <a href="{% url "user:list" %}">Regresar</a>
    </p>
{% endblock  %}

user/templates/user/user_detail.html
{% extends 'base.html' %}
{% block title %}
    {{ block.super }}
    Detalle Usuario
{% endblock title %}

{{% block content %}
    <h3>{{ user.name }}</h3>
    <p>Email: <i>{{ user.email }}</i></p>
    <p>Telefono: <i>{{ user.phone }}</i></p>
    <p> 
        <a href="{% url "user:edit" user.id %}">Editar</a> | 
        <a href="{% url "user:delete" user.id %}">Borrar</a> 
    </p>
    <p>
        <a href="{% url "user:list" %}">Regresar</a>
    </p>
{% endblock content %}}

user/templates/user/user_form.html
{% extends 'base.html' %}
{% block title %}
    {{ block.super }}
    Crear usuario
{% endblock  %}
{% block content %}
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Crear Usuario" />
    </form>
{% endblock content %}

user/templates/user/user_list.html
{% extends 'base.html' %}
{% block title %}
    {{ block.super }}
    Home
{% endblock  %}
{% block content %}
    <ul>
        {% for user in object_list %}
            <li>
                <a href="{% url "user:detail" user.id %}">{{ user.name }}</a>
            </li>
        {% endfor %}
    </ul>
{% endblock  %}